spring:
  application:
    name: its-system # (옵션) 애플리케이션의 이름을 지정합니다.
  datasource:
    url: "jdbc:mysql://software-engineering-proj.c3yaiomygurx.eu-north-1.rds.amazonaws.com:3306/software-engineering?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver # (옵션) 드라이버 클래스를 명시적으로 지정할 수 있습니다.
    jpa:
      database-platform: org.hibernate.dialect.MySQL8Dialect # (옵션) 데이터베이스 플랫폼에 맞는 적절한 값을 설정합니다.
      hibernate:
        ddl-auto: update # (옵션) 애플리케이션 시작 시 DDL을 자동으로 생성할지 여부를 설정합니다. (예: create, update, none 등)
        open-in-view: false
        show-sql: true
      properties:
        hibernate:
          format_sql: true